version: 2.0
machine:
  node:
    version: 8.5.0
dependencies:
  pre:
    - npm install angular-cli@latest -g
compile:
  override:
    - cd jjack-ui && npm install && ng build
deployment:
  prod:
    branch: master
    commands:
      - aws s3 sync jjack-ui/dist s3://jjack-hackathon/ --delete
