version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10.0
    working_directory: /jjack-ui
    steps:
      - checkout
      - run: npm install -g @angular/cli
      - run: npm install
      - run: ng build
      - deploy:
        name: Deploy to S3
        command: aws s3 sync jjack-ui/dist s3://jjack-hackathon/ --delete
